/**
 * Ultima Octave — the "Cube" visual skin. Not illustration: a composition of precise components.
 * Each minor is a flat field in its virtue's colour-cube colour + the octave's emblem + a top-centre
 * 3-bit watermark (Truth/Love/Courage as empty/filled circles) + a faint lunar mark; majors are the
 * proper nouns as single luminous emblems on graphite. Generated by tools/cube/cube_build.py.
 */
import { registerImagePack, registerPack } from "@/runtime/defineCard";

const files = import.meta.glob("./cube/*.png", { eager: true, query: "?url", import: "default" }) as Record<string, string>;
const urls: Record<string, string> = {};
for (const [path, url] of Object.entries(files)) {
  const slug = path.slice(path.lastIndexOf("/") + 1).replace(/\.png$/, "");
  urls[slug] = url;
}

registerImagePack("ultima-octave", "cube", urls);
registerPack("ultima-octave", { id: "cube", label: "Cube", description: "the colour-cube of virtue — flat fields, octave emblems, a 3-bit watermark" });
