/**
 * Ultima Octave Tarot — registered for the app. A companion to the Ultima Tarot built on Garriott's
 * 3-bit virtue algebra (Truth=4, Love=2, Courage=1 -> the 8 colour-cube corners). A lattice deck:
 *   suits       — the 8 VIRTUES (each a colour-cube corner; carries colour + binary subset + prime/composite)
 *   ranks       — the 8 OCTAVES (Virtue · Place · Role · Companion · Word · Stone · Reagent · Shrine),
 *                 each an upright/inverted duality; a card is "{octave} of {virtue}" (Place of Justice = Yew)
 *   transversal — "The Lunar Cycle" (Felucca's 8 phases / moongates), weather across the lattice
 *   majors      — the proper nouns of Britannia (the Avatar, Lord British, the Guardian, the Shadowlords…)
 *
 * Generated by tools/gen/gen_octave.py. Data-complete (86/86); a visual skin is pending.
 */
import deckJson from "@decks/ultima-octave/deck.json";
import { registerDeck } from "../registry";
import type { DeckDataFile, DeckModule } from "../types";
import type { CardData } from "@/runtime/types";

const data = deckJson as unknown as DeckDataFile;

export const ultimaOctaveDeck: DeckModule = registerDeck({
  id: "ultima-octave",
  name: data.name,
  tagline: "Eight virtues, eight octaves — Garriott's colour-cube of virtue as a lattice deck.",
  data,
  cards: Object.values(data.cards) as CardData[],
});
